services:
  - type: web
    name: wimbledon-village-hoa
    env: static
    branch: phase-0.5  # change this if your branch is different
    buildCommand: "npm install && ng build --configuration production"
    publishPath: "dist/wimbledon-village-hoa/browser"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        status: 200