services:
  - type: web
    name: wimbledon-village-hoa
    env: static
    branch: main 
    buildCommand: "ng build --configuration production"
    publishPath: "dist/wimbledon-village-hoa"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html